"use client";

import { animated, useSpring, useInView } from "@react-spring/web";
import { githubContributions as data } from "@/content/github-contributions";
import { usePrefersReducedMotion } from "@/lib/motion-preferences";

/** Public, verifiable list of the user's PRs into a given upstream repo. */
function prSearchUrl(repo: string): string {
  return `https://github.com/search?q=author%3A${data.user}+type%3Apr+repo%3A${encodeURIComponent(repo)}&type=pullrequests`;
}

/** Big, confident numbers: total PRs, merged shown only when it isn't zero. */
function UpstreamStats() {
  return (
    <div className="grid grid-cols-2 gap-px bg-border lg:grid-cols-1">
      {data.upstream.map((repo) => (
        <a
          key={repo.key}
          href={prSearchUrl(repo.repo)}
          target="_blank"
          rel="noopener noreferrer"
          className="group flex h-full flex-col justify-center bg-bg-raised px-5 py-4 transition-colors hover:bg-bg-raised/60"
          aria-label={`${repo.total} pull requests to ${repo.label}${repo.merged > 0 ? `, ${repo.merged} merged` : ""}`}
        >
          <p className="font-mono text-[0.65rem] uppercase tracking-wide text-text-muted transition-colors group-hover:text-text-primary">
            {repo.label}
          </p>
          <p className="mt-1 font-display text-4xl leading-none text-text-primary transition-colors group-hover:text-accent-add">
            {repo.total}
            <span className="ml-1.5 align-middle font-mono text-xs text-text-muted">
              PRs
            </span>
          </p>
          {repo.merged > 0 && (
            <p className="mt-1.5 font-mono text-xs text-accent-add">
              {repo.merged} merged
            </p>
          )}
        </a>
      ))}
    </div>
  );
}

export function ContributionsSection() {
  const reduced = usePrefersReducedMotion();
  const [inViewRef, inView] = useInView({ rootMargin: "-10% 0px", once: true });
  const springs = useSpring({
    from: { opacity: 0, y: 24 },
    to: { opacity: inView || reduced ? 1 : 0, y: inView || reduced ? 0 : 24 },
    config: { tension: 110, friction: 24 },
  });

  const { total, activeDays, bestDay } = data.calendar;

  return (
    <section
      id="contributions"
      ref={inViewRef as React.Ref<HTMLElement>}
      className="overflow-hidden bg-bg px-6 py-16 md:px-12 md:py-20"
      aria-labelledby="contributions-heading"
    >
      <animated.div
        style={{ opacity: springs.opacity, transform: springs.y.to((y) => `translate3d(0, ${y}px, 0)`) }}
        className="mx-auto max-w-6xl"
      >
        <div className="mb-8 flex flex-wrap items-end justify-between gap-x-8 gap-y-4">
          <div>
            <p className="font-mono text-xs uppercase text-accent-add">
              git shortlog
            </p>
            <h2
              id="contributions-heading"
              className="mt-2 font-display text-2xl md:text-3xl"
            >
              A year of commits, in three dimensions.
            </h2>
          </div>

          <dl className="flex gap-6 font-mono text-sm">
            <div>
              <dt className="text-[0.65rem] uppercase text-text-muted">total</dt>
              <dd className="mt-0.5 text-xl text-accent-add">{total}</dd>
            </div>
            <div>
              <dt className="text-[0.65rem] uppercase text-text-muted">active days</dt>
              <dd className="mt-0.5 text-xl text-text-primary">{activeDays}</dd>
            </div>
            <div>
              <dt className="text-[0.65rem] uppercase text-text-muted">best day</dt>
              <dd className="mt-0.5 text-xl text-text-primary">
                {bestDay?.count ?? 0}
                <span className="ml-1 text-[0.65rem] text-text-muted">
                  {bestDay?.date.slice(5)}
                </span>
              </dd>
            </div>
          </dl>
        </div>

        {/* One panel: the commit skyline and the upstream numbers side by side. */}
        <div className="grid gap-px border border-border bg-border lg:grid-cols-5">
          <figure className="bg-bg-raised/40 p-2 lg:col-span-3 md:p-3">
            {/* Generated by yoshi389111/github-profile-3d-contrib with the
                site's amber palette (scripts/3d-contrib-settings.json),
                language pie rethemed by scripts/theme-contrib-svg.mjs.
                Refresh: npm run fetch:contrib-svg */}
            {/* eslint-disable-next-line @next/next/no-img-element -- static SVG from /public; next/image adds nothing and requires dangerouslyAllowSVG */}
            <img
              src="/github-3d-contrib.svg"
              alt={`3D isometric contribution calendar: ${total} contributions across ${activeDays} active days in the last 12 months`}
              className="h-auto w-full"
              loading="lazy"
            />
            <figcaption className="px-1 pb-1 pt-2 font-mono text-[0.65rem] text-text-muted">
              github-profile-3d-contrib · palette: amber phosphor v2
            </figcaption>
          </figure>

          <div className="flex flex-col bg-bg lg:col-span-2">
            <p className="px-5 pt-5 font-mono text-xs uppercase text-accent-add">
              upstream — PRs into the frameworks I use
            </p>
            <div className="flex-1 py-px">
              <UpstreamStats />
            </div>
            <p className="px-5 pb-4 pt-3 font-mono text-[0.65rem] text-text-muted">
              states as of{" "}
              {new Date(data.fetchedAt).toISOString().slice(0, 10)} · live from
              the GitHub search API
            </p>
          </div>
        </div>
      </animated.div>
    </section>
  );
}
